baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Women's Wealth Coalition"
buildFuture = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]]

[params]
images = ["img/og-image.jpg"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
