baseurl = "https://womenswealthcoalition.com/"
languageCode = "en-us"
languageLang = "en"
title = "Women's Wealth Coalition"
buildFuture = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  images = ["images/OG.png"]
  description = "A community aligned to advance knowledge about women's wealth."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
