baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Women's Wealth Coalition"
buildFuture = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  images = ["img/OG.png"]
  description = "A community aligned to advance knowledge about women's wealth."
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
